name: Bug report
description: Report a bug in plugin commands, skills, agents, rules, or templates.
title: "bug: "
labels: ["bug"]
body:
  - type: input
    id: cursor_version
    attributes:
      label: Cursor version
      placeholder: "e.g. 2.5.x"
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
      placeholder: "e.g. 1.7.0"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: What happened
      description: Describe the observed behavior.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Provide minimal, numbered steps.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and artifacts
      description: Paste relevant logs, screenshots, or links.
