#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
commands=(
  "implement-flutter-feature.md"
  "implement-figma-screen.md"
  "generate-flutter-tests.md"
  "review-flutter-code.md"
  "security-review.md"
  "update-flutter-dependencies.md"
  "resolve-flutter-build-error.md"
  "prepare-mobile-release.md"
  "sync-official-flutter-ai-rules.md"
  "integrate-firebase.md"
)

report_file="${repo_root}/docs/quality-iterations-2026-02-21.md"

{
  echo "# Plugin Quality Iterations (2026-02-21)"
  echo
  echo "Automated quality audit over 10 command iterations."
  echo
  echo "| Iteration | Command | Frontmatter | Skill/Workflow Ref | Output Contract | Steps >= 4 | Status |"
  echo "|---:|---|---|---|---|---|---|"
} > "${report_file}"

idx=1
all_pass=true

for cmd in "${commands[@]}"; do
  path="${repo_root}/commands/${cmd}"
  content="$(cat "${path}")"

  has_frontmatter="fail"
  has_skill_or_workflow="fail"
  has_output_contract="fail"
  has_min_steps="fail"
  status="FAIL"

  if grep -Eq '^---' "${path}" && grep -Eq '^name:' "${path}" && grep -Eq '^description:' "${path}"; then
    has_frontmatter="pass"
  fi

  if grep -Eq '(\.\./skills/|templates/|docs/)' "${path}"; then
    has_skill_or_workflow="pass"
  fi

  if grep -Eq 'command-output-contract' "${path}"; then
    has_output_contract="pass"
  fi

  step_count="$(grep -Ec '^[0-9]+\.' "${path}" || true)"
  if [ "${step_count}" -ge 4 ]; then
    has_min_steps="pass"
  fi

  if [ "${has_frontmatter}" = "pass" ] && \
     [ "${has_skill_or_workflow}" = "pass" ] && \
     [ "${has_output_contract}" = "pass" ] && \
     [ "${has_min_steps}" = "pass" ]; then
    status="PASS"
  else
    all_pass=false
  fi

  echo "| ${idx} | \`${cmd%.md}\` | ${has_frontmatter} | ${has_skill_or_workflow} | ${has_output_contract} | ${has_min_steps} | **${status}** |" >> "${report_file}"
  idx=$((idx + 1))
done

{
  echo
  echo "## Findings"
  echo
  echo "- Stabilized command output with a shared contract: \`docs/command-output-contract.md\`."
  echo "- Canonical command set now references the output contract for deterministic response shape."
  echo "- This report is generated by \`scripts/quality_audit_commands.sh\`."
} >> "${report_file}"

if [ "${all_pass}" = false ]; then
  echo "Quality audit failed. See ${report_file}" >&2
  exit 1
fi

echo "Quality audit passed. Report: ${report_file}"
